name: GitHub Integration Continue API
on: [push]

jobs:
  build-and-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run unit tests 
        run: yarn test
        
  push_to_docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [build-and-test, build-and-test-e2e]
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build app
        run: yarn build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./api
          push: true
          tags: jamil18/tp3-github-actions:${{ github.sha }}
        
  build-and-test-e2e:
    name: Run integration tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    services:
      mongo:
        image: mongo
        ports:
          - '27017:27017'
        env:
          MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install dependencies
        run: yarn install --immutable 

      - name: Run integration Tests
        run: yarn test:e2e
        env:
          MONGODB_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@localhost:27017
